# Generated by Django 6.0.1 on 2026-02-01 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_perfil_delete_productolaboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconocimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reconocimientos/'),
        ),
    ]
