# Generated by Django 6.0.1 on 2026-02-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_curso_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoLaboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
