# Generated by Django 6.0 on 2026-02-02 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_productolaboral'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoacademico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_academicos/'),
        ),
        migrations.AddField(
            model_name='productolaboral',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos_laborales/'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='ventagaraje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='garaje/'),
        ),
    ]
