# Generated by Django 6.0 on 2026-02-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_productoacademico_imagen_productolaboral_imagen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoacademico',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AlterField(
            model_name='productoacademico',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
