# Generated by Django 6.0 on 2026-02-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_productoacademico_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productolaboral',
            name='fecha',
        ),
        migrations.AddField(
            model_name='productolaboral',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
