# Generated by Django 6.0 on 2026-02-02 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0008_remove_productolaboral_fecha_productolaboral_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventagaraje',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ventas/'),
        ),
        migrations.AlterField(
            model_name='ventagaraje',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ventagaraje',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
